apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-storage
  namespace: monitoring
  labels:
    app: grafana
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
