apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-storage
  namespace: monitoring
  labels:
    type: nfs
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/pv0001/